/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.util.Date;
import POJO.*;
import DAO.*;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ha Chi
 */
public class FormLichPhucKhao extends javax.swing.JFrame {

    /**
     * Creates new form FormLichPhucKhao
     */
    public FormLichPhucKhao() {
        initComponents();
        LoadLichPhucKhao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLuuLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllichphuckhao = new javax.swing.JTable();
        lblDangNhap = new javax.swing.JLabel();
        dtcngaybatdau = new com.toedter.calendar.JDateChooser();
        dtcngayketthuc = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ngày bắt đầu:");

        jLabel2.setText("Ngày kết thúc:");

        btnLuuLai.setText("Lưu lại");
        btnLuuLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuLaiActionPerformed(evt);
            }
        });

        tbllichphuckhao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ));
        jScrollPane1.setViewportView(tbllichphuckhao);

        lblDangNhap.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblDangNhap.setForeground(new java.awt.Color(51, 51, 255));
        lblDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangNhap.setText("LỊCH PHÚC KHẢO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtcngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtcngayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnLuuLai, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(lblDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDangNhap)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtcngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(dtcngayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuuLai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuLaiActionPerformed
        Date ngaybatdau = dtcngaybatdau.getDate();
        Date ngaykethuc = dtcngayketthuc.getDate();
        LichPhucKhao exp = new LichPhucKhaoDAO().laythongtintheoID(1);
        if (exp != null) {
            exp.setNgayBatDau(ngaybatdau);
            exp.setNgayKetThuc(ngaykethuc);
            boolean KQ = new LichPhucKhaoDAO().capnhatlichphuckhao(exp);
            if (KQ == true) {
                JOptionPane.showMessageDialog(this, "Bạn đã tạo lịch thành công");
                LoadLichPhucKhao();
            } else {
                JOptionPane.showMessageDialog(this, "Bạn đã tạo lịch không thành công");
            }
        }
    }//GEN-LAST:event_btnLuuLaiActionPerformed

    private void LoadLichPhucKhao() {
        List<LichPhucKhao> lst = new LichPhucKhaoDAO().laythongtin();
        tbllichphuckhao.setRowHeight(30);
        DefaultTableModel model = (DefaultTableModel) tbllichphuckhao.getModel();
        model.setRowCount(0);
        String[] columnsName = {"STT", "Ngày bắt đầu phúc khảo", "Ngày kết thúc phúc khảo"};
        model.setColumnIdentifiers(columnsName);
        lst.stream().map((exp) -> {
            Vector row = new Vector();
            row.add(exp.getId());
            SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
            row.add(dt.format(exp.getNgayBatDau()));
            SimpleDateFormat dt1 = new SimpleDateFormat("dd/MM/yyyy");
            row.add(dt1.format(exp.getNgayBatDau()));
            return row;
        }).forEachOrdered((row) -> {
            model.addRow(row);
        });
        tbllichphuckhao.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuLai;
    private com.toedter.calendar.JDateChooser dtcngaybatdau;
    private com.toedter.calendar.JDateChooser dtcngayketthuc;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JTable tbllichphuckhao;
    // End of variables declaration//GEN-END:variables
}
