/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import DAO.*;
import POJO.*;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Ha Chi
 */
public class FormDSPhucKhao extends javax.swing.JFrame {

    /**
     * Creates new form FormDSPhucKhao
     */
    public FormDSPhucKhao() {
        initComponents();
        LoadDanhSachPhucKhao();
    }
    
    private void LoadDanhSachPhucKhao() {
        List<PhucKhaoDiem> lst = new PhucKhaoDiemDAO().laythongtinphuckhaodiem();
        tblDanhSachPhucKhao.setRowHeight(30);
        DefaultTableModel model = (DefaultTableModel) tblDanhSachPhucKhao.getModel();
        model.setRowCount(0);
        String[] columnsName = {"STT", "Mã số sinh viên", "Họ tên", "Môn thi", "Lớp môn học", "Cột điểm cần phúc khảo", "Điểm mong muốn", "Lí do", "Ngày đăng ký", "Tình trạng phúc khảo"};
        model.setColumnIdentifiers(columnsName);
        int i = 1;
        for (PhucKhaoDiem rp : lst) {
            Vector row = new Vector();
            String number = Integer.toString(i);
            row.add(number);
            row.add(rp.getStudentId());
            Student st = new StudentDAO().laythongtinsinhvientheoID(rp.getStudentId());
            row.add(st.getFullname());
            MonHoc su = new MonHocDAO().laythongtinmonhoctheoID(rp.getMaMon());
            row.add(su.getTenMon());
            row.add(rp.getMaLop() + '-' + rp.getMaMon());
            row.add(rp.getCotDiemCanPhucKhao());
            row.add(rp.getDiemMongMuon());
            row.add(rp.getLiDo());
            SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
            row.add(dt.format(rp.getNgayDangKy()));
            TableColumn column = tblDanhSachPhucKhao.getColumnModel().getColumn(9);
            JComboBox<String> cbb = new JComboBox<>();
            List<TinhTrangPhucKhao> list = new TinhTrangPhucKhaoDAO().laythongtin();
            list.forEach((str) -> {
                cbb.addItem(str.getTenTinhTrangPhucKhao());
            });
            column.setCellEditor(new DefaultCellEditor(cbb));
            TinhTrangPhucKhao sr = new TinhTrangPhucKhaoDAO().laythongtintheoID(rp.getIdTinhTrang());
            row.add(sr.getTenTinhTrangPhucKhao());
            model.addRow(row);
            i++;
        }
        tblDanhSachPhucKhao.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLuuLai = new javax.swing.JButton();
        spDanhSach = new javax.swing.JScrollPane();
        tblDanhSachPhucKhao = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("DANH SÁCH PHÚC KHẢO");

        btnLuuLai.setText("Lưu lại");
        btnLuuLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuLaiActionPerformed(evt);
            }
        });

        tblDanhSachPhucKhao.setAutoCreateRowSorter(true);
        tblDanhSachPhucKhao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDanhSachPhucKhao.setOpaque(false);
        spDanhSach.setViewportView(tblDanhSachPhucKhao);

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(spDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addComponent(btnLuuLai, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuuLai, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(spDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuLaiActionPerformed
        boolean kq = false;
        DefaultTableModel model = (DefaultTableModel) tblDanhSachPhucKhao.getModel();
        int rows = tblDanhSachPhucKhao.getRowCount();
        for (int row = 0; row < rows; row++) {
            String studentid = model.getValueAt(row, 1).toString();
            String malopmonhoc = model.getValueAt(row, 4).toString();
            String[] malop = malopmonhoc.split("-");
            String tinhtrangphuckhao = model.getValueAt(row, 9).toString();
            TinhTrangPhucKhao sta = new TinhTrangPhucKhaoDAO().laythongtintheoten(tinhtrangphuckhao);
            PhucKhaoDiem pkd = new PhucKhaoDiemDAO().laythongtintheostudentidvamamon(studentid, malop[0], malop[1]);
            if (pkd != null) {
                pkd.setIdTinhTrang(sta.getId());
                kq = new PhucKhaoDiemDAO().capnhatphuckhao(pkd);
            }
        }
        if (kq == true) {
            JOptionPane.showMessageDialog(this, "Bạn đã cập nhật thành công");
            
        } else {
            JOptionPane.showMessageDialog(this, "Bạn đã cập nhật không thành công");
        }
    }//GEN-LAST:event_btnLuuLaiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuLai;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane spDanhSach;
    private javax.swing.JTable tblDanhSachPhucKhao;
    // End of variables declaration//GEN-END:variables
}
