/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

/**
 *
 * @author Ha Chi
 */
public class FormBangDiem extends javax.swing.JFrame {

    /**
     * Creates new form FormBangDiem
     */
    public FormBangDiem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThongTinDiem1 = new javax.swing.JPanel();
        lblthongtin1 = new javax.swing.JLabel();
        lblMSSV1 = new javax.swing.JLabel();
        txtMSSV1 = new javax.swing.JTextField();
        lblHoTen1 = new javax.swing.JLabel();
        txtHoten1 = new javax.swing.JTextField();
        lblDiemGiuaKy1 = new javax.swing.JLabel();
        txtDiemGiuaKy1 = new javax.swing.JTextField();
        lblDiemCuoiKy1 = new javax.swing.JLabel();
        txtDiemCuoiKy1 = new javax.swing.JTextField();
        lblDiemKhac1 = new javax.swing.JLabel();
        txtDiemKhac1 = new javax.swing.JTextField();
        lblDiemTong1 = new javax.swing.JLabel();
        txtDiemTong1 = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnKetQuaDiem = new javax.swing.JPanel();
        spDanhSachDiem = new javax.swing.JScrollPane();
        tblDanhSachDiem = new javax.swing.JTable();
        btnBangDiem = new javax.swing.JButton();
        cbxLop = new javax.swing.JComboBox<>();
        lblDau = new javax.swing.JLabel();
        lblRot = new javax.swing.JLabel();
        txtDau = new javax.swing.JTextField();
        txtRot = new javax.swing.JTextField();
        lblTiLe = new javax.swing.JLabel();
        lblTiLe1 = new javax.swing.JLabel();
        txtTileDau = new javax.swing.JTextField();
        txtTiLeRot = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnThongTinDiem1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Chi Tiết"));

        lblthongtin1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblthongtin1.setForeground(new java.awt.Color(51, 51, 255));
        lblthongtin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthongtin1.setText("THÔNG TIN ĐIỂM CỦA SINH VIÊN");
        lblthongtin1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMSSV1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMSSV1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMSSV1.setText("Mã số sinh viên:");
        lblMSSV1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtMSSV1.setEditable(false);

        lblHoTen1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblHoTen1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHoTen1.setText("Họ tên sinh viên:");
        lblHoTen1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtHoten1.setEditable(false);

        lblDiemGiuaKy1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDiemGiuaKy1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiemGiuaKy1.setText("Điểm giữa kỳ:");
        lblDiemGiuaKy1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblDiemCuoiKy1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDiemCuoiKy1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiemCuoiKy1.setText("Điểm cuối kỳ:");
        lblDiemCuoiKy1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblDiemKhac1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDiemKhac1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiemKhac1.setText("Điểm khác:");
        lblDiemKhac1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblDiemTong1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDiemTong1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiemTong1.setText("Điểm tổng:");
        lblDiemTong1.setFocusable(false);
        lblDiemTong1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnEdit.setText(" Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout pnThongTinDiem1Layout = new javax.swing.GroupLayout(pnThongTinDiem1);
        pnThongTinDiem1.setLayout(pnThongTinDiem1Layout);
        pnThongTinDiem1Layout.setHorizontalGroup(
            pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                .addComponent(lblthongtin1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDiemTong1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiemKhac1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiemCuoiKy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiemGiuaKy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHoTen1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(lblMSSV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMSSV1)
                            .addComponent(txtHoten1)
                            .addComponent(txtDiemGiuaKy1)
                            .addComponent(txtDiemCuoiKy1)
                            .addComponent(txtDiemKhac1)
                            .addComponent(txtDiemTong1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)))
                    .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThongTinDiem1Layout.setVerticalGroup(
            pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblthongtin1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMSSV1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMSSV1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblHoTen1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addComponent(txtHoten1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblDiemGiuaKy1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addComponent(txtDiemGiuaKy1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiemCuoiKy1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemCuoiKy1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiemKhac1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemKhac1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiemTong1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemTong1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnKetQuaDiem.setBorder(javax.swing.BorderFactory.createTitledBorder("Kết Quả Điểm Của Sinh Viên"));
        pnKetQuaDiem.setToolTipText("");

        tblDanhSachDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDanhSachDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachDiemMouseClicked(evt);
            }
        });
        spDanhSachDiem.setViewportView(tblDanhSachDiem);

        btnBangDiem.setText("Import Bảng Điểm");
        btnBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangDiemActionPerformed(evt);
            }
        });

        cbxLop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbxLop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLopItemStateChanged(evt);
            }
        });
        cbxLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLopActionPerformed(evt);
            }
        });

        lblDau.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDau.setText("SÔ SINH VIÊN ĐẬU:");

        lblRot.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRot.setText("SỐ SINH VIÊN RỚT:");

        txtDau.setEditable(false);
        txtDau.setBackground(new java.awt.Color(153, 153, 153));
        txtDau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtRot.setEditable(false);
        txtRot.setBackground(new java.awt.Color(153, 153, 153));
        txtRot.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblTiLe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTiLe.setText("TỈ LỆ: ");

        lblTiLe1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTiLe1.setText("TỈ LỆ: ");

        txtTileDau.setEditable(false);
        txtTileDau.setBackground(new java.awt.Color(153, 153, 153));
        txtTileDau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtTiLeRot.setEditable(false);
        txtTiLeRot.setBackground(new java.awt.Color(153, 153, 153));
        txtTiLeRot.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnKetQuaDiemLayout = new javax.swing.GroupLayout(pnKetQuaDiem);
        pnKetQuaDiem.setLayout(pnKetQuaDiemLayout);
        pnKetQuaDiemLayout.setHorizontalGroup(
            pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                        .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cbxLop, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBangDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                                        .addComponent(lblRot, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtRot))
                                    .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                                        .addComponent(lblDau, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDau, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                                        .addComponent(lblTiLe, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTileDau, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                                        .addComponent(lblTiLe1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTiLeRot)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spDanhSachDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnKetQuaDiemLayout.setVerticalGroup(
            pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBangDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(cbxLop))
                .addGap(44, 44, 44)
                .addComponent(spDanhSachDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDau, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDau, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiLe, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTileDau, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRot)
                        .addComponent(lblTiLe1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTiLeRot, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnThongTinDiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pnKetQuaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnKetQuaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnThongTinDiem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblDanhSachDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachDiemMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblDanhSachDiemMouseClicked

    private void btnBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangDiemActionPerformed
        
    }//GEN-LAST:event_btnBangDiemActionPerformed

    private void cbxLopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLopItemStateChanged
        
    }//GEN-LAST:event_cbxLopItemStateChanged

    private void cbxLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBangDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBangDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBangDiem;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox<String> cbxLop;
    private javax.swing.JLabel lblDau;
    private javax.swing.JLabel lblDiemCuoiKy;
    private javax.swing.JLabel lblDiemCuoiKy1;
    private javax.swing.JLabel lblDiemGiuaKy;
    private javax.swing.JLabel lblDiemGiuaKy1;
    private javax.swing.JLabel lblDiemKhac;
    private javax.swing.JLabel lblDiemKhac1;
    private javax.swing.JLabel lblDiemTong;
    private javax.swing.JLabel lblDiemTong1;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblHoTen1;
    private javax.swing.JLabel lblMSSV;
    private javax.swing.JLabel lblMSSV1;
    private javax.swing.JLabel lblRot;
    private javax.swing.JLabel lblTiLe;
    private javax.swing.JLabel lblTiLe1;
    private javax.swing.JLabel lblthongtin;
    private javax.swing.JLabel lblthongtin1;
    private javax.swing.JPanel pnKetQuaDiem;
    private javax.swing.JPanel pnThongTinDiem;
    private javax.swing.JPanel pnThongTinDiem1;
    private javax.swing.JScrollPane spDanhSachDiem;
    private javax.swing.JTable tblDanhSachDiem;
    private javax.swing.JTextField txtDau;
    private javax.swing.JTextField txtDiemCuoiKy;
    private javax.swing.JTextField txtDiemCuoiKy1;
    private javax.swing.JTextField txtDiemGiuaKy;
    private javax.swing.JTextField txtDiemGiuaKy1;
    private javax.swing.JTextField txtDiemKhac;
    private javax.swing.JTextField txtDiemKhac1;
    private javax.swing.JTextField txtDiemTong;
    private javax.swing.JTextField txtDiemTong1;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtHoten1;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtMSSV1;
    private javax.swing.JTextField txtRot;
    private javax.swing.JTextField txtTiLeRot;
    private javax.swing.JTextField txtTileDau;
    // End of variables declaration//GEN-END:variables
}
