/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import DAO.*;
import POJO.*;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ha Chi
 */
public class FormBangDiem extends javax.swing.JFrame {

    private final JFileChooser filestudyResult;
    private String filename;

    /**
     * Creates new form FormBangDiem
     */
    public FormBangDiem() {
        initComponents();
        filestudyResult = new JFileChooser();
        filestudyResult.setCurrentDirectory(new File("C:\\Users\\Ha Chi\\Desktop"));
        filestudyResult.setFileFilter(new FileNameExtensionFilter("File CSV", "csv"));
        filestudyResult.setMultiSelectionEnabled(true);
        LoadLopMonHoc();
        String malop = cbxLop.getItemAt(0);
        String[] ma = malop.split("-");
        LoadDiemSinhVien(ma[0], ma[1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThongTinDiem1 = new javax.swing.JPanel();
        lblthongtin1 = new javax.swing.JLabel();
        lblMSSV1 = new javax.swing.JLabel();
        txtmaSSV = new javax.swing.JTextField();
        lblHoTen1 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblDiemGiuaKy1 = new javax.swing.JLabel();
        txtDiemGK = new javax.swing.JTextField();
        lblDiemCuoiKy1 = new javax.swing.JLabel();
        txtDiemCK = new javax.swing.JTextField();
        lblDiemKhac1 = new javax.swing.JLabel();
        txtDiemKhac = new javax.swing.JTextField();
        lblDiemTong1 = new javax.swing.JLabel();
        txtDiemTong = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnNhapLai = new javax.swing.JButton();
        pnKetQuaDiem = new javax.swing.JPanel();
        spDanhSachDiem = new javax.swing.JScrollPane();
        tblDanhSachDiem = new javax.swing.JTable();
        btnBangDiem = new javax.swing.JButton();
        cbxLop = new javax.swing.JComboBox<>();
        lblDau = new javax.swing.JLabel();
        lblRot = new javax.swing.JLabel();
        txtDau = new javax.swing.JTextField();
        txtRot = new javax.swing.JTextField();
        lblTiLe = new javax.swing.JLabel();
        lblTiLe1 = new javax.swing.JLabel();
        txtTileDau = new javax.swing.JTextField();
        txtTiLeRot = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnThongTinDiem1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Chi Tiết"));

        lblthongtin1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblthongtin1.setForeground(new java.awt.Color(51, 51, 255));
        lblthongtin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthongtin1.setText("THÔNG TIN ĐIỂM CỦA SINH VIÊN");
        lblthongtin1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMSSV1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMSSV1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMSSV1.setText("Mã số sinh viên:");
        lblMSSV1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtmaSSV.setEditable(false);

        lblHoTen1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblHoTen1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHoTen1.setText("Họ tên sinh viên:");
        lblHoTen1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtHoTen.setEditable(false);

        lblDiemGiuaKy1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDiemGiuaKy1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiemGiuaKy1.setText("Điểm giữa kỳ:");
        lblDiemGiuaKy1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblDiemCuoiKy1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDiemCuoiKy1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiemCuoiKy1.setText("Điểm cuối kỳ:");
        lblDiemCuoiKy1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblDiemKhac1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDiemKhac1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiemKhac1.setText("Điểm khác:");
        lblDiemKhac1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblDiemTong1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDiemTong1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiemTong1.setText("Điểm tổng:");
        lblDiemTong1.setFocusable(false);
        lblDiemTong1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnEdit.setText("Chỉnh sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnNhapLai.setText("Nhập lại");
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThongTinDiem1Layout = new javax.swing.GroupLayout(pnThongTinDiem1);
        pnThongTinDiem1.setLayout(pnThongTinDiem1Layout);
        pnThongTinDiem1Layout.setHorizontalGroup(
            pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                .addComponent(lblthongtin1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDiemTong1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiemKhac1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiemCuoiKy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiemGiuaKy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHoTen1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(lblMSSV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmaSSV)
                            .addComponent(txtHoTen)
                            .addComponent(txtDiemGK)
                            .addComponent(txtDiemCK)
                            .addComponent(txtDiemKhac)
                            .addComponent(txtDiemTong, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)))
                    .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThongTinDiem1Layout.setVerticalGroup(
            pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblthongtin1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMSSV1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmaSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblHoTen1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnThongTinDiem1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblDiemGiuaKy1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addComponent(txtDiemGK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiemCuoiKy1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemCK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiemKhac1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiemTong1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemTong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnThongTinDiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnKetQuaDiem.setBorder(javax.swing.BorderFactory.createTitledBorder("Kết Quả Điểm Của Sinh Viên"));
        pnKetQuaDiem.setToolTipText("");

        tblDanhSachDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDanhSachDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachDiemMouseClicked(evt);
            }
        });
        spDanhSachDiem.setViewportView(tblDanhSachDiem);

        btnBangDiem.setText("Import Bảng Điểm");
        btnBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangDiemActionPerformed(evt);
            }
        });

        cbxLop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbxLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLopActionPerformed(evt);
            }
        });

        lblDau.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDau.setText("SỐ SINH VIÊN ĐẬU:");

        lblRot.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRot.setText("SỐ SINH VIÊN RỚT:");

        txtDau.setEditable(false);
        txtDau.setBackground(new java.awt.Color(255, 51, 51));
        txtDau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDau.setForeground(new java.awt.Color(255, 0, 51));

        txtRot.setEditable(false);
        txtRot.setBackground(new java.awt.Color(255, 51, 51));
        txtRot.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblTiLe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTiLe.setText("TỈ LỆ: ");

        lblTiLe1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTiLe1.setText("TỈ LỆ: ");

        txtTileDau.setEditable(false);
        txtTileDau.setBackground(new java.awt.Color(255, 51, 51));
        txtTileDau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTileDau.setForeground(new java.awt.Color(255, 51, 51));

        txtTiLeRot.setEditable(false);
        txtTiLeRot.setBackground(new java.awt.Color(255, 51, 51));
        txtTiLeRot.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnKetQuaDiemLayout = new javax.swing.GroupLayout(pnKetQuaDiem);
        pnKetQuaDiem.setLayout(pnKetQuaDiemLayout);
        pnKetQuaDiemLayout.setHorizontalGroup(
            pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                        .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cbxLop, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBangDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                                        .addComponent(lblRot, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtRot))
                                    .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                                        .addComponent(lblDau, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDau, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                                        .addComponent(lblTiLe, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTileDau, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                                        .addComponent(lblTiLe1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTiLeRot)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spDanhSachDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnKetQuaDiemLayout.setVerticalGroup(
            pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKetQuaDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBangDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(cbxLop))
                .addGap(44, 44, 44)
                .addComponent(spDanhSachDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDau, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiLe, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTileDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnKetQuaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRot)
                        .addComponent(lblTiLe1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTiLeRot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnThongTinDiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pnKetQuaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnKetQuaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnThongTinDiem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void LoadLopMonHoc() {
        List<ThoiKhoaBieu> lst = new ThoiKhoaBieuDAO().layThongTinThoiKhoaBieu();
        lst.forEach((lop) -> {
            cbxLop.addItem(lop.getMaLop() + '-' + lop.getMaMon());
        });
    }

    public void LoadDiemSinhVien(String malop, String mamon) {
        List<BangDiem> lst = new BangDiemDAO().layTheoMaMonAndMaLop(malop, mamon);
        if (lst != null) {
            DefaultTableModel model = (DefaultTableModel) tblDanhSachDiem.getModel();
            model.setRowCount(0);
            String[] columnsName = {"STT", "MSSV", "Họ tên", "Điểm giữa kỳ", "Điểm cuối kỳ", "Điểm khác", "Điểm tổng kết", "Kết quả"};
            model.setColumnIdentifiers(columnsName);
            int i = 1;
            for (BangDiem sr : lst) {
                Vector row = new Vector();
                String number = Integer.toString(i);
                row.add(number);
                row.add(sr.getStudentID());
                Student st = new StudentDAO().laythongtinsinhvientheoID(sr.getStudentID());
                row.add(st.getFullname());
                row.add(sr.getDiemGK());
                row.add(sr.getDiemCK());
                row.add(sr.getDiemKhac());
                row.add(sr.getDiemTong());
                String KQ;
                if (sr.getDiemTong() < 5) {
                    KQ = "Rớt";
                } else {
                    KQ = "Đậu";
                }
                row.add(KQ);
                model.addRow(row);
                i++;
            }
            tblDanhSachDiem.setModel(model);
            int Dau = 0, Rot = 0, TileDau, TileRot;
            int size = lst.size();
            for (int j = 0; j < size; j++) {
                if (lst.get(j).getDiemTong() >= 5) {
                    Dau = Dau + 1;
                } else {
                    Rot = Rot + 1;
                }
            }
            txtDau.setText(Integer.toString(Dau));
            txtRot.setText(Integer.toString(Rot));
            int tong = Dau + Rot;
            TileDau = ((Dau * 100) / tong);
            TileRot = ((Rot * 100) / tong);
            txtTileDau.setText(Integer.toString(TileDau) + "%");
            txtTiLeRot.setText(Integer.toString(TileRot) + "%");
        }

    }

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        filename = (String) cbxLop.getSelectedItem();
        String[] file = filename.split("-");
        String mssv = txtmaSSV.getText();
        String Hoten = txtHoTen.getText();
        float DiemGK = Float.parseFloat(txtDiemGK.getText());
        float DiemCK = Float.parseFloat(txtDiemCK.getText());
        float DiemKhac = Float.parseFloat(txtDiemKhac.getText());
        float DiemTong = Float.parseFloat(txtDiemTong.getText());
        BangDiem bd = new BangDiemDAO().layTheoMaLopMaMonAndStudentID(file[0], file[1], mssv);
        if (bd != null) {
            bd.setDiemGK(DiemGK);
            bd.setDiemCK(DiemCK);
            bd.setDiemKhac(DiemKhac);
            bd.setDiemTong(DiemTong);
            boolean kq = new BangDiemDAO().updateBangDiem(bd);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Bạn đã cập nhật thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Bạn đã cập nhật không thành công");
            }
        }
        LoadDiemSinhVien(file[0], file[1]);
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblDanhSachDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachDiemMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDanhSachDiem.getModel();
        int selectedRowIndex = tblDanhSachDiem.getSelectedRow();
        txtmaSSV.setEditable(false);
        txtmaSSV.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtHoTen.setText(model.getValueAt(selectedRowIndex, 2).toString());
        txtDiemGK.setText(model.getValueAt(selectedRowIndex, 3).toString());
        txtDiemCK.setText(model.getValueAt(selectedRowIndex, 4).toString());
        txtDiemKhac.setText(model.getValueAt(selectedRowIndex, 5).toString());
        txtDiemTong.setText(model.getValueAt(selectedRowIndex, 6).toString());
    }//GEN-LAST:event_tblDanhSachDiemMouseClicked

    public static String filename(String str, char sep, char ext) {
        String fullpath = str;
        int dot1 = fullpath.lastIndexOf(ext);
        int sep1 = fullpath.lastIndexOf(sep);
        return fullpath.substring(sep1 + 1, dot1);
    }

    private void btnBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangDiemActionPerformed
        int returnvalue = filestudyResult.showOpenDialog(this);
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            File[] files = filestudyResult.getSelectedFiles();
            for (File file : files) {
                try {
                    filename = file.toString();
                    String fi = filename(filename, '\\', '-');
                    String mh = filename(filename, '-', '.');
                    List<String> listImportDS = new BangDiemDAO().layThongTinImportFileCSV(filename);
                    int size = listImportDS.size();
                    for (int i = 0; i < size; i++) {
                        String[] str = listImportDS.get(i).split(",");
                        BangDiem bd = new BangDiem();
                        bd.setMaLop(fi);
                        bd.setMaMon(mh);
                        bd.setStudentID(str[0]);
                        bd.setDiemGK(Float.parseFloat(str[2]));
                        bd.setDiemCK(Float.parseFloat(str[3]));
                        bd.setDiemKhac(Float.parseFloat(str[4]));
                        bd.setDiemTong(Float.parseFloat(str[5]));
                        new BangDiemDAO().insertBangDiem(bd);
                    }
                    LoadDiemSinhVien(fi, mh);
                    cbxLop.removeAllItems();
                    LoadLopMonHoc();
                    cbxLop.removeItemAt(0);
                    cbxLop.setSelectedItem(fi + "-" + mh);
                } catch (IOException | NumberFormatException ex) {
                    ex.getMessage();
                }
            }
        }
    }//GEN-LAST:event_btnBangDiemActionPerformed

    private void cbxLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLopActionPerformed
        filename = (String) cbxLop.getSelectedItem();
        String[] ma = filename.split("-");
        LoadDiemSinhVien(ma[0], ma[1]);
    }//GEN-LAST:event_cbxLopActionPerformed

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
       txtmaSSV.setText("");
       txtHoTen.setText("");
       txtDiemGK.setText("");
       txtDiemCK.setText("");
       txtDiemKhac.setText("");
       txtDiemTong.setText("");
    }//GEN-LAST:event_btnNhapLaiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBangDiem;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JComboBox<String> cbxLop;
    private javax.swing.JLabel lblDau;
    private javax.swing.JLabel lblDiemCuoiKy1;
    private javax.swing.JLabel lblDiemGiuaKy1;
    private javax.swing.JLabel lblDiemKhac1;
    private javax.swing.JLabel lblDiemTong1;
    private javax.swing.JLabel lblHoTen1;
    private javax.swing.JLabel lblMSSV1;
    private javax.swing.JLabel lblRot;
    private javax.swing.JLabel lblTiLe;
    private javax.swing.JLabel lblTiLe1;
    private javax.swing.JLabel lblthongtin1;
    private javax.swing.JPanel pnKetQuaDiem;
    private javax.swing.JPanel pnThongTinDiem1;
    private javax.swing.JScrollPane spDanhSachDiem;
    private javax.swing.JTable tblDanhSachDiem;
    private javax.swing.JTextField txtDau;
    private javax.swing.JTextField txtDiemCK;
    private javax.swing.JTextField txtDiemGK;
    private javax.swing.JTextField txtDiemKhac;
    private javax.swing.JTextField txtDiemTong;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtRot;
    private javax.swing.JTextField txtTiLeRot;
    private javax.swing.JTextField txtTileDau;
    private javax.swing.JTextField txtmaSSV;
    // End of variables declaration//GEN-END:variables
}
